### ISSUE TITLE
Question: Is just a landing page clone?

### ISSUE THREAD

**Issue by jrichardsz** [app-clones/netflix-clone#285]
Is just a landing page clone? or it is possible to reproduce the video hosted in somewhere?
Thanks

**Comment by Beatzoid** [comment]
So far, the only features of this website are to register/log in, view details about a movie, and pop up a small video player (which currently just rick rolls you). I haven't put actual movies on the website because I'm 90% sure that's illegal, but if you have other suggestions of what I could put in place of the movies please share them.

**Comment by jrichardsz** [comment]
You could use [The Movie Database (TMDB) API](https://developers.themoviedb.org/3/getting-started/introduction) to fetch the images and movie description.

Also if it tries to be a clone of netflix could offer options to load videos from several sources like:

- Amazon S3
- Streaming (rtmp)
- Iptv (m3u8)

I'm trying to startup some other samples unlucky:

- https://github.com/ridhwaans/homehost
- https://github.com/owncast/owncast/issues/1417
- https://github.com/josh231101/Netflix-clone
- https://github.com/amoldalwai/watch-any-movie
- https://github.com/awebmekhilef/nodeflix
